services:
  - type: web
    name: workout-generator-api
    env: ruby
    rubyVersion: 3.1.4
    buildCommand: |
      gem install bundler:2.4.22
      bundle _2.4.22_ config set --local deployment 'false'
      bundle _2.4.22_ install
    startCommand: bundle exec ruby workout_generator.rb
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        sync: false 