services:
  - type: web
    name: workout-generator-api
    env: ruby
    plan: free
    buildCommand: |
      gem install bundler
      bundle install
    startCommand: bundle exec ruby workout_generator.rb
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        sync: false 